db.host=127.0.0.1
db.port=3306
db.username=root
db.pass=root
db.name=sportshoes

# Google reCAPTCHA v2
recaptcha.site.key=6LfGO6YsAAAAAC7swE3j4PVEqnJSEtumJl6LLTdg
recaptcha.secret.key=6LfGO6YsAAAAADWhpXdCfdIKQwArcEmehrW0E5eG

