db.host=127.0.0.1
db.port=3306
db.username=root
db.pass=
db.name=sportshoes

# Google reCAPTCHA v2
recaptcha.site.key=6LfGO6YsAAAAAC7swE3j4PVEqnJSEtumJl6LLTdg
recaptcha.secret.key=6LfGO6YsAAAAADWhpXdCfdIKQwArcEmehrW0E5eG

# MoMo Sandbox (Dev/Test)
momo.partner.code=MOMOLRJZ20181206
momo.access.key=mTCKt9W3eU1m39TW
momo.secret.key=SetA5RDnLHvt51AULf51DyauxUo3kDU6
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.return.url=http://localhost:8080/ShopShoes/momo/ket-qua
momo.ipn.url=https://oblivion-grievance-nectar.ngrok-free.dev/ShopShoes/momo/thong-bao
momo.request.type=captureWallet

#GHN api key
api.ghn=17a0a285-4b66-11f1-a973-aee5264794df
api.ghn.shopId=200241
api.ghn.province=https://dev-online-gateway.ghn.vn/shiip/public-api/master-data/province
api.ghn.district=https://dev-online-gateway.ghn.vn/shiip/public-api/master-data/district?province_id=
api.ghn.ward=https://dev-online-gateway.ghn.vn/shiip/public-api/master-data/ward?district_id=
api.ghn.fee=https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee