mail.host=smtp.gmail.com
mail.port=587
mail.username=quy231653@gmail.com
mail.password=sigy scei mpmd wczd
mail.auth=true
mail.starttls.enable=true
mail.smtp.ssl.trust=smtp.gmail.com
shop.name=BHD Sport Shoes
shop.hotline=0123.456.789
shop.address=Tr\u01b0\u1eddng \u0110\u1ea1i H\u1ecdc N\u00f4ng L\u00e2m TP.HCM
shop.email=23130061@st.hcmuaf.edu.vn